### ISSUE TITLE
Reddit Dataset Has Bugs

### ISSUE THREAD

**Issue by WMX567** [QueuQ/SSM#3]
Hi, 

When I ran the codes on Reddit Dataset. It has the following errors.

```
error Expected data to have 2000 rows, got 1993.
Traceback (most recent call last):
  File "/scratch1/mengxiwu/NLGL/train.py", line 162, in <module>
    AP, AF, acc_matrix = main(args,valid=True)
  File "/scratch1/mengxiwu/NLGL/pipeline.py", line 244, in pipeline_class_IL_no_inter_edge_minibatch
    life_model_ins.observe_class_IL_batch(args, subgraph, dataloader, features, labels, task, train_ids, ids_per_cls, dataset)
  File "/scratch1/mengxiwu/NLGL/Baselines/ssm_model.py", line 80, in observe_class_IL_batch
    output_predictions,_ = self.net.forward_batch(blocks, input_features)
  File "/scratch1/mengxiwu/NLGL/Backbones/gnns.py", line 108, in forward_batch
    logits, e = self.gat_layers[-1].forward_batch(blocks[-1], h)
  File "/scratch1/mengxiwu/NLGL/Backbones/gnnconv.py", line 187, in forward_batch
    block.update_all(gcn_msg, gcn_reduce)
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/heterograph.py", line 4786, in update_all
    self._set_n_repr(dtid, ALL, ndata)
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/heterograph.py", line 4049, in _set_n_repr
    self._node_frames[ntid].update(data)
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/frame.py", line 700, in __setitem__
    self.update_column(name, data)
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/frame.py", line 790, in update_column
    % (self.num_rows, len(col))
dgl._ffi.base.DGLError: Expected data to have 2000 rows, got 1993.

error happens on 
 errors/no_inter_task_edges/cls_IL/train_ratio_0.6/val_Reddit-CL_ssm_GCN_bs2000_['d_samp', 100, 0, 1]_bce0_bs2000
Traceback (most recent call last):
  File "/scratch1/mengxiwu/NLGL/train.py", line 205, in <module>
    AP_test, AF_test, acc_matrix_test = main(args, valid=False)
  File "/scratch1/mengxiwu/NLGL/pipeline.py", line 251, in pipeline_class_IL_no_inter_edge_minibatch
    model = pickle.load(open(save_model_path,'rb')).cuda(args.gpu)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/mengxiwu/NLGL/results/ssm/Reddit-CL/val_models/val_Reddit-CL_ssm_GCN_bs2000_200_3_bce0_0_[0, 1].pkl'
```

Any idea? Thanks!

**Comment by Vic-GoodLuck** [comment]
Same Question
